version: '3'
services:
  benares:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benares_container
    volumes:
      - "/home/persi/projects/Benares/logs:/root/.npm/_logs"
      - "/home/persi/projects/Benares/assets:/usr/src/app/assets"
      - "/home/persi/projects/Benares/db.json:/usr/src/app/db.json"
      - "/home/persi/projects/Benares/.env:/usr/src/app/.env"
    restart: no
