version: '3'
services:
  benares_test:
    image: benares_test
    container_name: benares_container_test
    volumes:
      - "/projects/Benares/logs_test:/root/.npm/_logs"
      - "/projects/Benares/assets:/usr/src/app/assets"
      - "/projects/Benares/db_test.json:/usr/src/app/db.json"
      - "/projects/Benares/.env:/usr/src/app/.env"
    restart: on-failure