name: Docker Image CI

on:
  push:
    branches: [ "main", "test" ]

jobs:

  build:

    runs-on: [Linux, X64]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Stop and remove the old container if it exists
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          DOCKER_CONTAINER="benares_container"
        else
          DOCKER_CONTAINER="benares_container_test"
        fi
        if [ "$(docker ps -a -q -f name=$DOCKER_CONTAINER)" ]; then
         docker stop $DOCKER_CONTAINER
         docker rm $DOCKER_CONTAINER
        fi

    - name: Stop and remove the old container if it exists
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          DOCKER_IMAGE="benares"
        else
          DOCKER_IMAGE="benares_test"
        fi
        if [ "$(docker images -q $DOCKER_IMAGE)" ]; then
            docker rmi $DOCKER_IMAGE
        fi
    
    - name: Build the Docker image
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          DOCKER_IMAGE="benares"
        else
          DOCKER_IMAGE="benares_test"
        fi
        docker build . --file Dockerfile --tag $DOCKER_IMAGE

    - name: Run the Docker container
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          DISCORD_TOKEN=${{ secrets.DISCORD_APP_TOKEN_PROD }}
          DOCKER_CONTAINER="benares_container"
        else
          DISCORD_TOKEN=${{ secrets.DISCORD_APP_TOKEN_TEST }}
          DOCKER_CONTAINER="benares_container_test"
        fi
        docker run \
          --detach \
          -v "/projects/Benares/assets:/usr/src/app/assets" \
          -v "/projects/Benares/db.json:/usr/src/app/db.json" \
          -e "DISCORD_TOKEN=$DISCORD_TOKEN" \
          -e "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
          --name $DOCKER_CONTAINER \
          benares
