name: Docker Image CI Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "test" ]

jobs:

  build:

    runs-on: [ Linux, X64 ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose-test.yml up --detach
