name: Docker Image CI

on:
  push:
    branches: [ "build" ]

jobs:

  build:

    runs-on: [Linux, X64]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag benares --rm

    - name: Remove dangling Docker images
      run: docker rmi $(docker images -f "dangling=true" -q)
