name: Docker Image CI

on:
  push:
    branches: [ "build" ]

jobs:

  build:

    runs-on: [Linux, X64]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag benares
