name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: [ 'Linux', 'X64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v3.2.0

    - name: Become a god
      run: echo ${{ secrets.USERPWD }} | sudo su

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.8.0
      with:
        dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
