name: Continuous Integration Test with Docker

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "test" ]

jobs:

  docker_build:

    runs-on: [ Linux, X64 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Environment
        run: docker-compose -f docker-compose.test.yml up --detach
